In [ ]:
# Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.


In [2]:
import numpy as np

In [8]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp


array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [7]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [10]:
c=(zp*ks).mean()-zp.mean()*ks.mean()
c

9157.839999999997

In [12]:
np.cov(zp,ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [27]:
npcov= np.cov(zp,ks,ddof=0)[0,1]
npcov

9157.840000000002

In [15]:
import pandas as pd

In [18]:
df = pd.DataFrame({'zp':zp, 'ks':ks}, columns = ['zp','ks'])
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [23]:
dfcov = df.cov().values[0,1]
dfcov

10175.377777777778

In [20]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

In [21]:
ks.std(ddof=1)

183.99544076477068

In [22]:
zp.std(ddof=1)

62.31318747531162

In [25]:
#несмещ
dfcov/(ks.std(ddof=1)*zp.std(ddof=1))

0.8874900920739162

In [31]:
#смещ
npcov/(ks.std()*zp.std())

0.8874900920739163

In [ ]:
# Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [32]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [ ]:
# критерий стьюдента

In [33]:
iq.mean()

118.1

In [34]:
a2 = 0.05/2
a2

0.025

In [35]:
df = len(iq) -1
df

9

In [40]:
tkrit = 2.62

In [41]:
iq.mean()-(tkrit*(iq.std(ddof=1))/((10)**0.5))

109.36273755051897

In [42]:
iq.mean()+(tkrit*(iq.std(ddof=1))/((10)**0.5))

126.83726244948102

In [ ]:
# Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [50]:
std = 5
n = 27
mu = 174.2
a2 = 0.05/2
a2

0.025

In [ ]:
# z критерий

In [47]:
z = 1.96

In [48]:
mu+(z*std/(n**0.5))

176.08601087935276

In [49]:
mu-(z*std/(n**0.5))

172.31398912064722