Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.
Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.
Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.
Задание 4**
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Выборочная ковариация и выборочная дисперсия — Студопедия
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1


In [107]:
import numpy as np

In [108]:
#1 
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)

print("Размерность a: {}".format(a.ndim))

print("Форма a: {}".format(a.shape))

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Размерность a: 2
Форма a: (5, 2)


In [109]:
mean_a = np.mean(a)
mean_a

5.2

Задание 2 Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [110]:
a_centered = a - mean_a
a_centered

array([[-4.2,  0.8],
       [-3.2,  2.8],
       [-2.2,  5.8],
       [-2.2,  4.8],
       [-4.2,  1.8]])

In [111]:
a_centered2 = np.subtract(a, mean_a)
a_centered2

array([[-4.2,  0.8],
       [-3.2,  2.8],
       [-2.2,  5.8],
       [-2.2,  4.8],
       [-4.2,  1.8]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [112]:
a_centered_sp = a_centered[0].dot(a_centered[1])
a_centered_sp

15.68

In [113]:
a_centered_sp / (len(a)-1)

3.92

In [114]:
a.shape, a.ndim

((5, 2), 2)

In [115]:
print(len(a[0])), print(len(a)) 

2
5


(None, None)

In [116]:
#4

In [117]:
a_transp = np.transpose(a)
a_transp


array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [118]:
np.cov(a_transp, ddof =1)

array([[1. , 2. ],
       [2. , 4.3]])

In [119]:
# не сошлось

In [120]:
np.cov(a)

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

Тема “Работа с данными в Pandas”
Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].
Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.
Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.
Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.
Задание 5**
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [121]:
import pandas as pd

In [122]:
author_id = [1, 2, 3]
author_name =  ['Тургенев', 'Чехов', 'Островский']
author_id, author_name

([1, 2, 3], ['Тургенев', 'Чехов', 'Островский'])

In [123]:
authors = pd.DataFrame(author_id, author_name)
authors

0
Тургенев    1
Чехов       2
Островский  3

In [124]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский'],})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [125]:
authors.shape, authors.columns, authors.index, authors.info

((3, 2),
 Index(['author_id', 'author_name'], dtype='object'),
 RangeIndex(start=0, stop=3, step=1),
 <bound method DataFrame.info of    author_id author_name
 0          1    Тургенев
 1          2       Чехов
 2          3  Островский>)

In [126]:
bbbb = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]}
books = pd.DataFrame(bbbb)
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [127]:
authors_price = pd.merge(authors, books, on= 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [128]:
authors_price.describe()

author_id       price
count   7.000000    7.000000
mean    1.857143  387.142857
std     0.899735   80.976187
min     1.000000  290.000000
25%     1.000000  325.000000
50%     2.000000  370.000000
75%     2.500000  450.000000
max     3.000000  500.000000

In [129]:
Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


SyntaxError: invalid syntax (<ipython-input-129-10e0f6d18a92>, line 1)

In [ ]:
authors_price[authors_price["author_name"].isnull()], authors_price[authors_price["author_name"].notnull()]

In [ ]:
authors_price.sort_values(by="price", inplace=True)
authors_price

In [ ]:
authors_price.reset_index(drop=True, inplace=True)
authors_price

In [ ]:
top5 = authors_price.nlargest(5, "price")
top5

#4 Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [ ]:
authors_price.describe()

In [ ]:
authors_price.loc[authors_price["price"].notnull(), "max_price"] = authors_price["price"].max()
authors_price

In [ ]:
authors_price.loc[authors_price["price"].notnull(), "min_price"] = authors_price["price"].min()
authors_price

In [ ]:
authors_price.loc[authors_price["price"].notnull(), "median_price"] = authors_price["price"].median()
authors_price

In [ ]:
authors_price.drop("author_id", axis =1, inplace = True)
authors_price

In [ ]:
authors_price.drop("book_title", axis =1, inplace = True)
authors_price

In [ ]:
authors_price

In [ ]:
authors_stat = authors_price.copy()
authors_stat 

In [ ]:
Задание 5**
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [ ]:
authors_stat.loc[authors_price["price"].notnull(), "cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_stat

In [ ]:
?pd.pivot_table

In [ ]:
pd.pivot_table(
    data = author_stat,
    values=price,
    index="author_name",
    columns="cover",
    aggfunc='mean',
    fill_value=None,
    margins=False,
    dropna=True,
    margins_name='All',
    observed=False,
)